name: libgen
description: Non-official Library Genesis mobile client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+4

environment:
  sdk: ">=2.7.0 <3.0.0"

  # See docs: https://pub.dev/packages/package_info
  package_info: ">=0.4.3+2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # Project-specific dependencies
  http: ^0.13.2
  flutter_bloc: ^6.0.6
  hydrated_bloc: ^6.1.0
  json_annotation: ^3.1.0
  flutter_downloader:
    git:
      url: git://github.com/manuelvargastapia/flutter_downloader.git # Patch solution to augment default timeout from 15s to 60s
      ref: timeout
  url_launcher: ^5.7.10
  downloads_path_provider: ^0.1.0
  permission_handler: ^5.0.1+1
  simple_html_css:
    git:
      url: git://github.com/manuelvargastapia/simple_html_css_flutter.git # Patch solution to prevent RangeError exception
      ref: fix_range_error
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  dartz: ^0.9.2
  expandable: ^4.1.4
  intl: ^0.17.0
  package_info: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Project-specific dependencies
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  hive_generator: ^0.8.2
  equatable: ^1.2.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo_light.png
    - assets/images/logo_dark.png
    - assets/images/app_icon.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf

flutter_intl:
  main_locale: en_US
  enabled: true
